@startuml
start
repeat :Vòng lặp FOR;
  
  if (Điều kiện lọc?) then (Khớp - ITER)
    #Pink:ITER;
    ' Buộc mũi tên quay thẳng về repeat while, bỏ qua node bên dưới
    goto end_loop
  else (Không khớp)
    :Xử lý logic chính;
    :Cập nhật dữ liệu;
  endif

  :handle other logic;

label end_loop
repeat while (Còn phần tử tiếp theo?) is (loop)
stop
@enduml